### ISSUE TITLE
Icon generation fails

### ISSUE THREAD

**Issue by jonasfunk** [tidev/liveview#224]
Getting this error frequently:

```
[ERROR] Error: Command failed: java -jar "~/Library/Application Support/Titanium/mobilesdk/osx/12.2.1.GA/node_modules/node-appc/tools/resizer/resizer.jar" "~/reshopper/build/iphone/DefaultIcon.png" "~/reshopper/build/iphone/Assets.xcassets/AppIcon.appiconset/appicon-Small@2x.png" 58 58 "~/reshopper/build/iphone/Assets.xcassets/AppIcon.appiconset/appicon-Small@3x.png" 87 87 "~/reshopper/build/iphone/Assets.xcassets/AppIcon.appiconset/appicon-Small-40@2x.png" 80 80 "~/reshopper/build/iphone/Assets.xcassets/AppIcon.appiconset/appicon-Small-40@3x.png" 120 120 "~/reshopper/build/iphone/Assets.xcassets/AppIcon.appiconset/appicon-60@2x.png" 120 120 "~/reshopper/build/iphone/Assets.xcassets/AppIcon.appiconset/appicon-60@3x.png" 180 180 "~/reshopper/build/iphone/Assets.xcassets/AppIcon.appiconset/appicon-Marketing.png" 1024 1024

at ChildProcess.exithandler (child_process.js:383:12)
    at ChildProcess.emit (events.js:400:28)
    at maybeClose (internal/child_process.js:1088:16)
    at Socket.<anonymous> (internal/child_process.js:446:11)
    at Socket.emit (events.js:400:28)
    at Pipe.<anonymous> (net.js:686:12)
```

**Comment by janvennemann** [comment]
@jonasfunk Can you provide additional context? When exactly does this happen? From the error message this looks more like an SDK issue instead of Liveview.

**Comment by jonasfunk** [comment]
It was when running ti serve ios. I think it might be because I had another liveview running in another project.
